// SPDX-License-Identifier: GPL-2.0-only
//! The concurrent write load that generic/464 applies, driven directly.
//!
//! The test itself takes three minutes: ten loops of five seconds of
//! load, each followed by an unmount, a full fsck and a remount, and it
//! stops at the first loop the check fails. Reproducing the leak that
//! way costs one answer per twenty minutes once a build is counted.
//!
//! The load is what matters, not the harness around it: sixteen
//! processes each truncating and rewriting a random file, appending to
//! another, and forcing writeback on a third, over two hundred files.
//! Applied on its own it reproduces in two to nine loops.
//!
//! Two details are not optional, both learnt the hard way.
//!
//! The filesystem is made once per series, not once per loop. Ten loops
//! on one volume is what the test does, and it is what fills the volume
//! and gets blocks recycled -- the regime the leak needs. Reformatting
//! every loop measures something else: 24494 contiguous blocks lost in
//! a single loop, against the 28 to 1400 the test produces.
//!
//! And the loop leaves nothing behind that breaks the next one. The
//! stop flag lives in a directory made by mktemp and removed when the
//! writers finish, so a killed run cannot leave a flag that makes the
//! next run's writers exit immediately -- which happened, and cost an
//! hour of a machine looping at full speed writing nothing.

use std::fmt::Write as _;
use std::time::Duration;

use crate::node::NodeConn;

/// How hard to push, and for how long.
#[derive(Clone, Copy)]
pub struct Load {
    /// Writers of each kind. The test uses 16.
    pub procs: u32,
    /// Distinct files they contend over. The test uses 200.
    pub files: u32,
    /// Seconds of load per loop. The test uses 5.
    pub secs: u32,
    /// Write size. The test uses 64 KiB.
    pub block: u32,
    /// Largest file, in blocks of `block`. The test uses 100.
    pub max_blocks: u32,
}

impl Default for Load {
    fn default() -> Self {
        // generic/464's own numbers: BLOCK_SZ=65536, MAXFILES=200,
        // PROC_CNT=16, LOOP_TIME=5, and pwrite up to 100 blocks.
        Self { procs: 16, files: 200, secs: 5, block: 65536, max_blocks: 100 }
    }
}

impl Load {
    pub fn from_env() -> Self {
        let mut l = Self::default();
        let get = |k: &str| std::env::var(k).ok().and_then(|v| v.parse::<u32>().ok());
        if let Some(v) = get("XFSTESTS_LOAD_PROCS") {
            l.procs = v;
        }
        if let Some(v) = get("XFSTESTS_LOAD_FILES") {
            l.files = v;
        }
        if let Some(v) = get("XFSTESTS_LOAD_SECS") {
            l.secs = v;
        }
        if let Some(v) = get("XFSTESTS_LOAD_BLOCK") {
            l.block = v;
        }
        if let Some(v) = get("XFSTESTS_LOAD_MAXBLK") {
            l.max_blocks = v;
        }
        l
    }

    pub fn describe(&self) -> String {
        format!(
            "{} writers x3 over {} files, {}s, {} KiB writes up to {} blocks",
            self.procs,
            self.files,
            self.secs,
            self.block / 1024,
            self.max_blocks
        )
    }
}

/// What one loop did.
pub struct LoopResult {
    /// Blocks fsck calls used-but-unreferenced.
    pub lost: Vec<u64>,
    /// Blocks fsck calls referenced-but-free, the opposite symptom.
    pub dangling: usize,
    /// Whether the filesystem was made at the start of this loop.
    pub formatted: bool,
}

/// Build the loop body.
///
/// Written out as a file and executed rather than passed as an argument:
/// the body needs $RANDOM, command substitution and its own variables,
/// and every layer between here and the remote shell is one more chance
/// to lose a quote.
fn script(l: &Load, dev: &str, mnt: &str, mkfs_opts: &str, fresh: bool) -> String {
    let mut s = String::with_capacity(2048);
    let _ = write!(
        s,
        r#"#!/bin/sh
# Generated by beamfs-xfstests; edits here are overwritten.
T=/sys/kernel/debug/tracing

echo cleanup > /tmp/beamfs-step
pkill -9 xfs_io 2>/dev/null
umount -l {mnt} 2>/dev/null
sleep 1
mkdir -p {mnt}
"#
    );
    if fresh {
        let _ = writeln!(
            s,
            "mkfs.beamfs {mkfs_opts} {dev} >/dev/null 2>&1 || {{ echo 'MKFS FAILED' >&2; exit 1; }}"
        );
    }
    let _ = write!(
        s,
        r#"echo mount > /tmp/beamfs-step
mount -t beamfs {dev} {mnt} || {{ echo 'MOUNT FAILED' >&2; exit 1; }}

: > $T/trace
echo 1 > $T/tracing_on

# The stop flag lives in a directory of its own, removed with the
# writers. A flag left in /tmp by a killed run makes the next run's
# writers exit at once and the loop spin doing nothing.
D=$(mktemp -d)
S=$D/stop

j=1
while [ $j -le {procs} ]; do
  ( while [ ! -e $S ]; do
      xfs_io -ftc "pwrite -b {block} 0 $(( (RANDOM % {max_blocks}) * {block} ))" \
        {mnt}/$((RANDOM % {files})) >/dev/null 2>&1
    done ) &
  ( while [ ! -e $S ]; do
      echo t >> {mnt}/$((RANDOM % {files})) 2>/dev/null
    done ) &
  ( while [ ! -e $S ]; do
      xfs_io -c "sync_range -w 0 0" {mnt}/$((RANDOM % {files})) >/dev/null 2>&1
    done ) &
  j=$(( j + 1 ))
done

echo load > /tmp/beamfs-step
sleep {secs}
touch $S
wait 2>/dev/null
rm -rf $D

# Tracing stays on across the unmount. Stopping it first and then
# concluding from the silence that unmount issued no synchronous
# writeback was an artefact of the window, and cost a day.
echo unmount > /tmp/beamfs-step
# A writer that outlived its kill keeps the mount busy, and one busy
# unmount must not end the loop: retry, then detach. A lazy unmount
# still detaches the filesystem, which is what fsck needs, and the
# stragglers die with their file descriptors.
umount {mnt} 2>/dev/null ||
  {{ sleep 2; pkill -9 xfs_io 2>/dev/null; sleep 1; umount {mnt} 2>/dev/null; }} ||
  umount -l {mnt} 2>/dev/null ||
  {{ echo 'UMOUNT FAILED' >&2; exit 1; }}
sleep 1
echo 0 > $T/tracing_on

# grep exits 1 when it matches nothing, and matching nothing is the
# good case: the loop was clean. Without the guard every clean loop is
# reported as a failed one.
echo fsck > /tmp/beamfs-step
fsck.beamfs -v {dev} 2>&1 > /tmp/beamfs-fsck.out
grep -oE '[0-9]+ referenced-but-free' /tmp/beamfs-fsck.out | grep -oE '^[0-9]+' | head -1 | sed 's/^/DANGLING /' || true
grep -oE 'block [0-9]+ marked' /tmp/beamfs-fsck.out | grep -oE '[0-9]+' || true
exit 0
"#,
        procs = l.procs,
        files = l.files,
        secs = l.secs,
        block = l.block,
        max_blocks = l.max_blocks,
    );
    s
}

/// Run one loop on `node` and report what fsck found.
pub fn run_loop(
    c: &NodeConn,
    l: &Load,
    dev: &str,
    mnt: &str,
    mkfs_opts: &str,
    fresh: bool,
    deadline: Duration,
) -> Result<LoopResult, String> {
    let body = script(l, dev, mnt, mkfs_opts, fresh);
    let tmp = std::env::temp_dir().join("beamfs-load-loop.sh");
    std::fs::write(&tmp, &body).map_err(|e| format!("write {}: {e}", tmp.display()))?;
    c.push(tmp.to_str().unwrap_or_default(), "/tmp/beamfs-load-loop.sh")
        .map_err(|e| format!("push: {e}"))?;

    let out = c
        .run("sudo sh /tmp/beamfs-load-loop.sh", deadline)
        .map_err(|e| e.to_string())?;

    let mut lost = Vec::new();
    let mut dangling = 0usize;
    for line in out.lines() {
        let t = line.trim();
        if let Some(rest) = t.strip_prefix("DANGLING ") {
            dangling = rest.parse().unwrap_or(0);
        } else if let Ok(b) = t.parse::<u64>() {
            lost.push(b);
        }
    }
    Ok(LoopResult { lost, dangling, formatted: fresh })
}

/// Enable the tracepoints and size the ring, once per campaign.
pub fn prepare(c: &NodeConn, mnt: &str, ring_kb: u32) -> Result<(), String> {
    let cmd = format!(
        "sudo sh -c 'pkill -9 xfs_io 2>/dev/null; mkdir -p {mnt}; \
         echo 1 > /sys/kernel/debug/tracing/events/beamfs/enable 2>/dev/null; \
         for e in writeback_dirty_inode writeback_write_inode \
                  writeback_single_inode_start writeback_queue writeback_exec; do \
           [ -d /sys/kernel/debug/tracing/events/writeback/$e ] && \
             echo 1 > /sys/kernel/debug/tracing/events/writeback/$e/enable; \
         done; echo {ring_kb} > /sys/kernel/debug/tracing/buffer_size_kb'"
    );
    c.run(&cmd, Duration::from_secs(120))
        .map(|_| ())
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_defaults_are_the_tests_own_numbers() {
        let l = Load::default();
        assert_eq!(l.procs, 16);
        assert_eq!(l.files, 200);
        assert_eq!(l.secs, 5);
        assert_eq!(l.block, 65536);
    }

    #[test]
    fn a_fresh_loop_formats_and_a_continuing_one_does_not() {
        let l = Load::default();
        let with = script(&l, "/dev/vdc", "/mnt/scratch", "-N 16384", true);
        let without = script(&l, "/dev/vdc", "/mnt/scratch", "-N 16384", false);
        assert!(with.contains("mkfs.beamfs"));
        assert!(!without.contains("mkfs.beamfs"));
    }

    #[test]
    fn the_stop_flag_is_removed_with_the_writers() {
        let s = script(&Load::default(), "/dev/vdc", "/mnt/scratch", "", false);
        assert!(s.contains("D=$(mktemp -d)"));
        assert!(s.contains("rm -rf $D"));
    }
}
